name: Events Demo 1
on:
  pull_request:
    types: # Activity Type, On event's which action workflow will execute
      - opened #Workflow will trigger when a pull(Merge) request create(Dev Branch -> Development Branch) in this repository
      - edited #Workflow will trigger when a pull(Merge) request edited in this repository
    branches:
      - "master"
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "Dev"
    path-ignore: # Ignore the execution of workflow, if delivery happen on below paths
      - ".github/workflows/*" # Workflow will not trigger if any push happen in path '.github/workflow/'
    # paths:
    # - ".github/workflows/*" # Opposite, workflow will only execute if push happened on the files path '.github/workflow/'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
